name: taskassassin
description: "TaskAssassin gamifies productivity by transforming your to-do list into exciting missions, complete with AI verification, personalized \"Handler\" coaches, and a vibrant social system."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  permission_handler: ^12.0.0
  image: ^4.0.0
  google_sign_in: '>=6.2.1'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  image_picker: '>=1.1.2'
  http: ^1.0.0
  provider: ^6.0.0
  go_router: ^17.0.0
  intl: 0.20.2
  uuid: ^4.0.0
  supabase_flutter: '>=1.10.0'
  google_generative_ai: ^0.4.7
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/taskassassin_logo.png
  remove_alpha_ios: true
